# Generated by Django 6.1 on 2026-08-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='smartphone', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aba_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('channel', models.CharField(choices=[('POS', 'In-Store POS'), ('ONLINE', 'E-Commerce Online')], default='POS', max_length=10)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_city', models.CharField(default='Phnom Penh', max_length=100)),
                ('delivery_district', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ABA_PAY', 'ABA Pay / KHQR'), ('CREDIT_CARD', 'Credit / Debit Card'), ('COD', 'Cash On Delivery')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending Payment'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fulfillment_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending Staff Review'), ('PACKING', 'Packing at Store'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('cashier_name', models.CharField(default='Cashier 01', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('wholesale_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Standard selling price', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Promotional price if active', max_digits=10, null=True)),
                ('image_url', models.TextField(blank=True)),
                ('requires_imei', models.BooleanField(default=True, help_text='Serialized mobile device tracking')),
                ('accessory_stock', models.IntegerField(default=0, help_text='Stock count for non-serialized accessories')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imeis_json', models.JSONField(blank=True, default=list)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, max_length=30, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available in Stock'), ('SOLD_POS', 'Sold via POS'), ('RESERVED_ONLINE', 'Reserved / Sold Online'), ('DEFECTIVE', 'Defective / RMA')], db_index=True, default='AVAILABLE', max_length=20)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_imeis', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='store.product')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
